#!/bin/sh

load_scull_driver() {
    module="$1"
    device="$2"
    mode="$3"

    echo "Loading $module driver"
    modprobe "$module"

    # Retrieve major number
    major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
    echo "$module major number: $major"

    # Remove stale nodes and replace them, then give gid and perms
    for i in {0..3}; do
        rm -f "/dev/$device$i"
        mknod "/dev/$device$i" c $major $i
    done

    ln -sf "${device}0" "/dev/$device"
    chgrp staff "/dev/$device"[0-3]
    chmod 664 "/dev/$device"[0-3]
}

unload_module() {
    module="$1"

    echo "Unloading $module module"
    rmmod "$module"
}

case "$1" in
    start)
        load_scull_driver "scull" "scull" 664
        load_scull_driver "faulty" "faulty" 664
        load_scull_driver "hello" "hello" 664
        ;;
    stop)
        unload_module "hello"
        unload_module "faulty"
        unload_module "scull"

        # Remove stale nodes
        rm -f /dev/scullull /dev/scull[0-3]
        rm -f /dev/scullpriv
        rm -f /dev/scullpipe /dev/scullpipe[0-3]
        rm -f /dev/scullsingle
        rm -f /dev/sculluid
        rm -f /dev/scullwuid
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
